version: '3.8'
services:
  db:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=petstore
    ports:
      - "3306:3306"
  adminer:
    image: adminer
    ports:
      - "8080:8080"